/**
 * Course creation page for teachers
 */

import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { useTranslation } from "react-i18next";
import { format } from "date-fns";
import { CalendarIcon } from "lucide-react";

import TeacherLayout from "@/components/layout/TeacherLayout";
import { useAuthContext } from "@/contexts/AuthContext";
import { useCourseMutations } from "@/hooks/useClasses";
import { ROUTES } from "@/config/constants";

import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Calendar } from "@/components/ui/calendar";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { TimePicker } from "@/components/ui/time-picker";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

// Form validation schema
const courseFormSchema = z.object({
  name: z
    .string()
    .min(3, "Navn må være minst 3 tegn")
    .max(100, "Navn kan ikke være mer enn 100 tegn"),
  description: z.string().optional(),
  numberOfWeeks: z
    .number()
    .min(1, "Antall uker må være minst 1")
    .max(52, "Antall uker kan ikke overstige 52"),
  startDate: z.date({ required_error: "Startdato er påkrevd" }),
  recurringTime: z
    .string()
    .regex(
      /^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$/,
      "Ugyldig tidsformat (bruk HH:MM)",
    ),
  duration: z
    .number()
    .min(15, "Varighet må være minst 15 minutter")
    .max(300, "Varighet kan ikke overstige 300 minutter"),
  capacity: z
    .number()
    .min(1, "Kapasitet må være minst 1")
    .max(100, "Kapasitet kan ikke overstige 100"),
  price: z.number().min(0, "Pris kan ikke være negativ"),
  location: z.string().min(2, "Lokasjon må være minst 2 tegn"),
});

type CourseFormValues = z.infer<typeof courseFormSchema>;

export default function CourseCreate() {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const { user } = useAuthContext();
  const { create, loading, error } = useCourseMutations();
  const [submitError, setSubmitError] = useState<string | null>(null);

  const form = useForm<CourseFormValues>({
    resolver: zodResolver(courseFormSchema),
    defaultValues: {
      name: "",
      description: "",
      numberOfWeeks: 8,
      startDate: new Date(),
      recurringTime: "18:00",
      duration: 75,
      capacity: 15,
      price: 1500,
      location: "",
    },
  });

  const onSubmit = async (values: CourseFormValues) => {
    try {
      setSubmitError(null);

      if (!user?.id) {
        setSubmitError("Du må være innlogget for å opprette et kurs");
        return;
      }

      await create({
        teacherId: user.id,
        name: values.name,
        description: values.description || undefined,
        numberOfWeeks: values.numberOfWeeks,
        startDate: values.startDate,
        recurringDayOfWeek: values.startDate.getDay(),
        recurringTime: values.recurringTime,
        duration: values.duration,
        capacity: values.capacity,
        price: values.price,
        location: values.location,
        sessions: [], // Sessions will be auto-generated by the service
      });

      // Navigate back to courses list on success
      navigate(ROUTES.TEACHER.COURSES);
    } catch (err) {
      setSubmitError(
        err instanceof Error ? err.message : "Kunne ikke opprette kurs",
      );
    }
  };

  return (
    <TeacherLayout>
      <div className="space-y-6">
        {/* Breadcrumb */}
        <Breadcrumb>
          <BreadcrumbList>
            <BreadcrumbItem>
              <BreadcrumbLink href={ROUTES.TEACHER.DASHBOARD}>
                Hjem
              </BreadcrumbLink>
            </BreadcrumbItem>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbLink href={ROUTES.TEACHER.COURSES}>
                Kurs
              </BreadcrumbLink>
            </BreadcrumbItem>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbPage>Opprett nytt</BreadcrumbPage>
            </BreadcrumbItem>
          </BreadcrumbList>
        </Breadcrumb>

        {/* Page Header */}
        <div>
          <h1 className="text-3xl font-normal text-foreground">
            Opprett nytt kurs
          </h1>
          <p className="mt-2 text-muted-foreground">
            Fyll ut skjemaet for å opprette et nytt yogakurs
          </p>
        </div>

        {/* Error Display */}
        {(submitError || error) && (
          <Card className="border-destructive/20 bg-destructive/5 rounded-2xl p-6">
            <p className="font-medium text-destructive/80">Noe gikk galt</p>
            <p className="text-sm mt-2 text-destructive/70">
              {submitError || error?.message}
            </p>
          </Card>
        )}

        {/* Form */}
        <Card className="p-8">
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-8">
              {/* Name */}
              <FormField
                control={form.control}
                name="name"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Kursnavn *</FormLabel>
                    <FormControl>
                      <Input
                        placeholder="F.eks. 8-ukers Hatha Yoga Grunnkurs"
                        {...field}
                      />
                    </FormControl>
                    <FormDescription>
                      Navnet på kurset som vises til studentene
                    </FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />

              {/* Description */}
              <FormField
                control={form.control}
                name="description"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Beskrivelse</FormLabel>
                    <FormControl>
                      <Textarea
                        placeholder="Beskriv kurset..."
                        className="min-h-[100px]"
                        {...field}
                      />
                    </FormControl>
                    <FormDescription>
                      En detaljert beskrivelse av hva kurset innebærer
                    </FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />

              {/* Number of Weeks and Start Date Row */}
              <div className="grid gap-4 md:grid-cols-2">
                {/* Number of Weeks */}
                <FormField
                  control={form.control}
                  name="numberOfWeeks"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Antall uker *</FormLabel>
                      <FormControl>
                        <Input
                          type="number"
                          {...field}
                          onChange={(e) =>
                            field.onChange(parseInt(e.target.value))
                          }
                        />
                      </FormControl>
                      <FormDescription>
                        Hvor mange uker kurset varer
                      </FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Start Date */}
                <FormField
                  control={form.control}
                  name="startDate"
                  render={({ field }) => (
                    <FormItem className="flex flex-col">
                      <FormLabel>Startdato *</FormLabel>
                      <Popover>
                        <PopoverTrigger asChild>
                          <FormControl>
                            <Button
                              variant="outline"
                              className="w-full justify-start text-left font-normal cursor-pointer"
                            >
                              <CalendarIcon className="mr-2 h-4 w-4" />
                              {field.value ? (
                                format(field.value, "dd.MM.yyyy")
                              ) : (
                                <span>Velg dato</span>
                              )}
                            </Button>
                          </FormControl>
                        </PopoverTrigger>
                        <PopoverContent className="w-auto p-0" align="start">
                          <Calendar
                            mode="single"
                            selected={field.value}
                            onSelect={field.onChange}
                            disabled={(date) =>
                              date < new Date(new Date().setHours(0, 0, 0, 0))
                            }
                            initialFocus
                          />
                        </PopoverContent>
                      </Popover>
                      <FormDescription>
                        Kurset gjentas hver uke på samme ukedag
                      </FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              {/* Time */}
              <FormField
                control={form.control}
                name="recurringTime"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Tidspunkt *</FormLabel>
                    <FormControl>
                      <TimePicker
                        value={field.value}
                        onChange={field.onChange}
                        placeholder="Velg tidspunkt"
                      />
                    </FormControl>
                    <FormDescription>Klokkeslett for hver økt</FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />

              {/* Duration, Capacity, Price Row */}
              <div className="grid gap-4 md:grid-cols-3">
                {/* Duration */}
                <FormField
                  control={form.control}
                  name="duration"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Varighet (min) *</FormLabel>
                      <FormControl>
                        <Input
                          type="number"
                          {...field}
                          onChange={(e) =>
                            field.onChange(parseInt(e.target.value))
                          }
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Capacity */}
                <FormField
                  control={form.control}
                  name="capacity"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Kapasitet *</FormLabel>
                      <FormControl>
                        <Input
                          type="number"
                          {...field}
                          onChange={(e) =>
                            field.onChange(parseInt(e.target.value))
                          }
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                {/* Price */}
                <FormField
                  control={form.control}
                  name="price"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Pris (NOK) *</FormLabel>
                      <FormControl>
                        <Input
                          type="number"
                          {...field}
                          onChange={(e) =>
                            field.onChange(parseInt(e.target.value))
                          }
                        />
                      </FormControl>
                      <FormDescription>
                        Totalpris for hele kurset
                      </FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              {/* Location */}
              <FormField
                control={form.control}
                name="location"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Lokasjon *</FormLabel>
                    <FormControl>
                      <Input placeholder="F.eks. Yoga Studio Oslo" {...field} />
                    </FormControl>
                    <FormDescription>Hvor kurset finner sted</FormDescription>
                    <FormMessage />
                  </FormItem>
                )}
              />

              {/* Info */}
              <div className="rounded-2xl border border-primary/20 bg-primary/5 p-4">
                <p className="text-sm text-primary">
                  <strong>Info:</strong> Kursøkter blir automatisk generert
                  basert på startdato, antall uker og valgt ukedag.
                </p>
              </div>

              {/* Form Actions */}
              <div className="flex gap-4">
                <Button
                  type="submit"
                  disabled={loading}
                  className="cursor-pointer"
                >
                  {loading ? "Oppretter..." : "Opprett kurs"}
                </Button>
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => navigate(ROUTES.TEACHER.COURSES)}
                  disabled={loading}
                  className="cursor-pointer"
                >
                  Avbryt
                </Button>
              </div>
            </form>
          </Form>
        </Card>
      </div>
    </TeacherLayout>
  );
}
