/**
 * Supabase Database Types
 *
 * These types will be automatically generated by Supabase CLI in production.
 * For now, we'll use placeholder types that match our schema.
 *
 * To generate actual types:
 * 1. Install Supabase CLI: npm install -g supabase
 * 2. Login: supabase login
 * 3. Generate types: supabase gen types typescript --project-id [your-project-id] > src/types/supabase.ts
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          name: string
          phone: string | null
          role: 'teacher' | 'student'
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          name: string
          phone?: string | null
          role: 'teacher' | 'student'
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          name?: string
          phone?: string | null
          role?: 'teacher' | 'student'
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      teacher_profiles: {
        Row: {
          id: string
          bio: string | null
          specialties: string[] | null
          website: string | null
        }
        Insert: {
          id: string
          bio?: string | null
          specialties?: string[] | null
          website?: string | null
        }
        Update: {
          id?: string
          bio?: string | null
          specialties?: string[] | null
          website?: string | null
        }
      }
      student_profiles: {
        Row: {
          id: string
          emergency_contact_name: string | null
          emergency_contact_phone: string | null
          emergency_contact_relationship: string | null
          medical_notes: string | null
        }
        Insert: {
          id: string
          emergency_contact_name?: string | null
          emergency_contact_phone?: string | null
          emergency_contact_relationship?: string | null
          medical_notes?: string | null
        }
        Update: {
          id?: string
          emergency_contact_name?: string | null
          emergency_contact_phone?: string | null
          emergency_contact_relationship?: string | null
          medical_notes?: string | null
        }
      }
      courses: {
        Row: {
          id: string
          teacher_id: string
          name: string
          description: string | null
          number_of_weeks: number
          start_date: string
          recurring_day_of_week: number
          recurring_time: string
          duration: number
          capacity: number
          price: number
          location: string
          enrolled_count: number
          image_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          teacher_id: string
          name: string
          description?: string | null
          number_of_weeks: number
          start_date: string
          recurring_day_of_week: number
          recurring_time: string
          duration: number
          capacity: number
          price: number
          location: string
          enrolled_count?: number
          image_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          teacher_id?: string
          name?: string
          description?: string | null
          number_of_weeks?: number
          start_date?: string
          recurring_day_of_week?: number
          recurring_time?: string
          duration?: number
          capacity?: number
          price?: number
          location?: string
          enrolled_count?: number
          image_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      events: {
        Row: {
          id: string
          teacher_id: string
          name: string
          description: string | null
          event_type: string
          date: string
          start_time: string
          duration: number
          capacity: number
          price: number
          location: string
          drop_in_available: boolean
          booked_count: number
          image_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          teacher_id: string
          name: string
          description?: string | null
          event_type: string
          date: string
          start_time: string
          duration: number
          capacity: number
          price: number
          location: string
          drop_in_available?: boolean
          booked_count?: number
          image_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          teacher_id?: string
          name?: string
          description?: string | null
          event_type?: string
          date?: string
          start_time?: string
          duration?: number
          capacity?: number
          price?: number
          location?: string
          drop_in_available?: boolean
          booked_count?: number
          image_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      bookings: {
        Row: {
          id: string
          student_id: string
          item_id: string
          item_type: 'course' | 'event'
          booking_date: string
          status: 'confirmed' | 'pending' | 'cancelled' | 'completed'
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          student_id: string
          item_id: string
          item_type: 'course' | 'event'
          booking_date?: string
          status: 'confirmed' | 'pending' | 'cancelled' | 'completed'
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          student_id?: string
          item_id?: string
          item_type?: 'course' | 'event'
          booking_date?: string
          status?: 'confirmed' | 'pending' | 'cancelled' | 'completed'
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      payments: {
        Row: {
          id: string
          booking_id: string
          student_id: string
          teacher_id: string
          amount: number
          currency: string
          status: 'paid' | 'pending' | 'overdue' | 'refunded'
          payment_method: string | null
          transaction_id: string | null
          paid_at: string | null
          due_date: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          booking_id: string
          student_id: string
          teacher_id: string
          amount: number
          currency?: string
          status: 'paid' | 'pending' | 'overdue' | 'refunded'
          payment_method?: string | null
          transaction_id?: string | null
          paid_at?: string | null
          due_date?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          booking_id?: string
          student_id?: string
          teacher_id?: string
          amount?: number
          currency?: string
          status?: 'paid' | 'pending' | 'overdue' | 'refunded'
          payment_method?: string | null
          transaction_id?: string | null
          paid_at?: string | null
          due_date?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      course_sessions: {
        Row: {
          id: string
          course_id: string
          session_number: number
          date: string
          start_time: string
          duration: number
          topic: string | null
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          course_id: string
          session_number: number
          date: string
          start_time: string
          duration: number
          topic?: string | null
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          course_id?: string
          session_number?: number
          date?: string
          start_time?: string
          duration?: number
          topic?: string | null
          notes?: string | null
          created_at?: string
        }
      }
      attendance: {
        Row: {
          id: string
          booking_id: string
          student_id: string
          session_id: string
          attended: boolean
          notes: string | null
          recorded_at: string
        }
        Insert: {
          id?: string
          booking_id: string
          student_id: string
          session_id: string
          attended?: boolean
          notes?: string | null
          recorded_at?: string
        }
        Update: {
          id?: string
          booking_id?: string
          student_id?: string
          session_id?: string
          attended?: boolean
          notes?: string | null
          recorded_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
